name = "shouna"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "shouna-db"
database_id = "be60fb77-0313-45e9-9ec1-ae42137a7ff4"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "shouna-photos"


