name = "shouna"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "shouna-db"
database_id = "211ff579-daf0-42d9-a680-10fc4870ca24"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "shouna-photos"


